### ISSUE TITLE
Update to ghx_grid 0.3 and bevy 0.14

### ISSUE THREAD

**Issue by Henauxg** [Henauxg/ghx_proc_gen#3]
Probably won't happen before the 15th of august

**Comment by a-panda-miner** [comment]
https://github.com/Henauxg/ghx_proc_gen/pull/4

**Comment by a-panda-miner** [comment]
[Made a pull request, it needs work still](https://github.com/Henauxg/ghx_proc_gen/pull/4)

**Comment by Henauxg** [comment]
`ghx_grid` update done in #2 
`bevy` update coming later or tomorrow
